/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_appsync_graphqlEndpoint": "https://kpwahj2qyjgyrfa2efw2rjwbpy.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-yore43yypzb5dlhhejh4mm5mpq",
  "aws_cognito_identity_pool_id": "us-east-1:39c74fe7-4eb5-46c1-8527-ba4861fe667b",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_kMlJhM0Gq",
  "aws_user_pools_web_client_id": "26dgnbcbrd92b162q2rpqsg04g",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 6,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ]
};


export default awsmobile;
