/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_appsync_graphqlEndpoint": "https://7rmncuazrjb67h4tmqm5iz2oaa.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-stfgncaykfhn7cm3ltpewbchf4",
  "aws_cognito_identity_pool_id": "us-east-1:42fb2493-29a6-4d3d-aa82-9f8339fc32b3",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_Y92pzhKjN",
  "aws_user_pools_web_client_id": "2f6lqs7h3q8946t5oc3p7r2gha",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 6,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ]
};


export default awsmobile;
